# Generated by Django 5.2.3 on 2025-06-17 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='crated_date',
            new_name='created_date',
        ),
    ]
