# Generated by Django 5.2.3 on 2025-06-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_crated_date_contact_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pictur',
            field=models.ImageField(blank=True, upload_to='picture/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
